### ISSUE TITLE
Interchangeable Ingredients (Question/Suggestion)

### ISSUE THREAD

**Issue by CantBeKarma** [Traqueur-dev/RecipesAPI#6]
Hello, I just recently discovered this API. Looks pretty neat. Just had a general question, is it at all possible at the moment to do something along the lines of multiple item ingredients per crafting recipe (as in, accepting either item)?

Basically allowing the recipe to support any of the listed items (for example, in the picture below, any type of plank in any order). If there is, would you mind including an example for the repo? Thanks!

![image_2024-09-13_151613883](https://github.com/user-attachments/assets/2084b152-eabb-4812-b8f0-695e48ee0036)

**Comment by CantBeKarma** [comment]
Funny enough, I just realized that using TagIngredient is a thing lol. So something along the lines of `new TagIngredient(org.bukkit.Tag.PLANKS, 'X')` would achieve what I'm looking for.

I'll leave this open because it should totally be an example within the readme, imo.

**Comment by Traqueur-dev** [comment]
Thank you for your message. Indeed, by using the TagIngredient class, you can have a list of materials that will be accepted as ingredients.

I haven’t finished writing the wiki yet, but I will add it and make sure to explain it thoroughly!

Feel free to check out the Javadoc in the meantime!
