### ISSUE TITLE
"Recipes" Folder

### ISSUE THREAD

**Issue by CantBeKarma** [Traqueur-dev/RecipesAPI#7]
With the latest version as of writing this, the whole **YML File Support for Custom Recipes** is pretty neat except I'm not currently planning on using this feature. Is there any way to prevent the creation of the "recipes" folder? Currently it's forcefully creating itself within my plugin's directory. Thanks!

**Comment by Traqueur-dev** [comment]
Indeed, at the moment I haven't coded a solution to disable the creation of the 'recipes' folder. I will go ahead and create it.

**Comment by Traqueur-dev** [comment]
@CantBeKarma https://github.com/Traqueur-dev/RecipesAPI/releases/tag/1.1.1
New Release available

**Comment by CantBeKarma** [comment]
> @CantBeKarma https://github.com/Traqueur-dev/RecipesAPI/releases/tag/1.1.1
> 
> New Release available.
> 
> 
> 
> I'll let you close the issue when you have read it.

Awesome. Thank you!
